### ISSUE TITLE
Doesn't work on osx terminal

### ISSUE THREAD

**Issue by claytongulick** [freeall/single-line-log#8]
Each log entry writes to a new line on mac... any way around this?

**Comment by freeall** [comment]
I'm on osx and I don't see this. Can you try to reproduce and show an example?

**Comment by freeall** [comment]
![image](https://cloud.githubusercontent.com/assets/376654/15571654/57d118a4-233c-11e6-8947-5ded43a04c97.png)

**Comment by mafintosh** [comment]
also haven't had any problems on mac myself
