### ISSUE TITLE
Issues with long lines

### ISSUE THREAD

**Issue by j-s-n** [freeall/single-line-log#9]
When I print out a long line that wraps off the edge of the console more than once (i.e. a string that takes at least 3 lines to print out), single-line-log seems to miss the first few lines of the output when clearing what it previously printed. So those lines repeat over and over.
To reproduce, try this, with the console resized so that long line wraps several times:
```
var log = require('single-line-log');
var msg = "this line should repeat \n long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string long string ";

setInterval(() => log.stdout(msg), 500);
```

I've verified with a number of different terminal emulators, it seems to be an issue with how single-line-log calculates what it needs to overwrite.

**Comment by freeall** [comment]
I can verify that this happens. I guess you're right that it's to do with the calculation.

Do you want to give it a go at fixing it?

**Comment by j-s-n** [comment]
Sure
